### ISSUE TITLE
Method call in another module does not get compiled correctly

### ISSUE THREAD

**Issue by ghewgill** [ghewgill/neon-lang#108]
It is currently possible to declare a method in a different module than the actual record declaration. This doesn't cause an error, but instead the function implementation is copied to the calling module bytecode (and doesn't work because the string table offsets are wrong).

From https://trello.com/c/iODYhpbd/276-string-startswith

**Comment by gitlarryf** [comment]
Can the string table offsets be "fixed up" so that this "behavior" can be exploited to allow over-riding functions that are built in to certain modules?  For example, if the user IMPORTs one of the Neon Libraries, then EXPORTs the IMPORTs, but writes a different function implementation, and calls it like StringEx.neon, or something?  This "feature" could come in handy, in that fashion, so long as we KNOW, and EXPECT this behavior from Neon.

**Comment by ghewgill** [comment]
No. This issue is most definitely a bug, not a feature.

**Comment by ghewgill** [comment]
I'm going to close this because I don't quite understand how one could get into this situation. It's possible to implement a method for a type declared elsewhere, but there's no way to export that method from a module. This may have been possible long ago, but I don't see how now.
