### ISSUE TITLE
SCons --clean option leaves folders in ./external

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#141]
When running an `scons -c` or `scons --clean`, there are two directories left behind in the /external directory.

- lib
- libressl-2.2.4/

Are the two folders left behind on at least the Win32 platform.  Note that libressl-2.2.4/ has multiple files, and another folder under it.  This makes it impossible to switch release modes without going into the external folder and deleting the folders by hand.

**Comment by ghewgill** [comment]
This appears to happen only on Windows. It seems to be due to the tar file containing some files lacking the "w" bit, which Python's tarfile module extracts as read-only files, which the shutil.rmtree function cannot remove.

A solution can be found in [Python - shutil.rmtree to remove readonly files](https://stackoverflow.com/questions/21261132/python-shutil-rmtree-to-remove-readonly-files).
