### ISSUE TITLE
toString() functions on RECORDs is not implicitly called.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#185]
When an object has a toString() function member, it is not implicitly called when used in a string function.  For example, the following code results in a type mismatch.

```
VAR foo: String := "Foo"

TYPE barStr IS RECORD
    val: String
END RECORD

FUNCTION barStr.toString(self: barStr): String
    RETURN " BAR: " & self.val
END FUNCTION

print("\(foo & barStr())") 
```

I think Neon should call the toString() member if the object has it, and it's used in a string function.

**Comment by ghewgill** [comment]
One of the design goals of Neon is to limit the number of implicit things that are automatically inserted by the compiler. Implicit calls can make the code much more difficult to follow because the source code doesn't reveal what is *actually* being called. 

I would prefer to leave this behavior as is, and reserve the automatic call to `.toString()` for simple cases of interpolation (not expression elements).
